name: aisweb
description: AISWeb Dart Package API (no official)
version: 1.0.0-aplha1
author: INFRACEA | Labs
homepage: https://infracea.com.br

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.3
  xml2json: ^5.2.0

dev_dependencies:
  test: ^1.17.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# about Semantic Versioning https://semver.org/

